services:
  postgres:
    image: postgres:16
    container_name: azlearn_postgres
    environment:
      POSTGRES_USER: azlearn
      POSTGRES_PASSWORD: azlearn123
      POSTGRES_DB: azlearn_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: azlearn_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: